feature: add new theme switching
UEK-i-team/team-homepage pull request #18
Opened 2024-01-09 17:46 UTC by szymonqqaz

2024-01-09 18:06 UTC, TheFenix2000 requested changes

2024-01-09 18:06 UTC, TheFenix2000 commented on src/components/TitleText/TitleText.js
ten cały komponent jest wgl do usuniecia, użycie i wytłumaczenei na kanale na serwerze napisz

2024-01-09 18:06 UTC, TheFenix2000 commented on yarn.lock
to do wywalenia i do do dodania do ignore'a

2024-01-09 18:26 UTC, szymonqqaz commented on src/components/TitleText/TitleText.js
Tak, wrzuciłem to tymczasowo do podglądu dla was

2024-01-09 18:29 UTC, TheFenix2000 commented on src/components/TitleText/TitleText.js
No nie, w sensie do wywalenia całkiem, ten komponent nadal jest w projekcie

2024-01-09 19:02 UTC, szymonqqaz commented on src/components/TitleText/TitleText.js
Wiem o co ci chodzi wywalę go

2024-01-13 17:16 UTC, TheFenix2000 approved these changes

2024-01-13 18:18 UTC, merged