feature: implement styles and desktop functionality
UEK-i-team/team-homepage pull request #20
Opened 2024-01-13 16:17 UTC by TheWoxPL

- added menu items of sidebar to navbar
- added styles for desktop navbar
- navbar works properly for screen widths over 950px

2024-01-15 14:46 UTC, szymonqqaz submitted a review, later dismissed
Wygląda super!

2024-01-16 13:33 UTC, TheFenix2000 requested changes
rebesuj na nowym developie i usuń konfikty

2024-01-16 18:48 UTC, TheWoxPL commented
> rebesuj na nowym developie i usuń konfikty

Zrobiłem rebase i czekam na approve by zrobic merge'a.

2024-01-17 19:33 UTC, TheFenix2000 submitted a review, later dismissed

2024-01-17 19:33 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.js
> +            isDarkTheme ? `${desktopMenu} ${desktopMenuDark}` : desktopMenu
używamy nowej funkcji od Szymona do zmiany klasy tła poczytaj tutaj https://discord.com/channels/894595800343134248/1183889743621136404/1195796215598682183

2024-01-17 19:33 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.js
>            <button id={isDarkTheme ? plDark : plLight}>PL</button>
tutaj analogicznei trzeba poprawić te ify na funkcje theme powyżej

2024-01-17 19:33 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.module.scss
> +@media screen and (min-width: $breakpoint-tablet) {
zmień breakpoint, czy też mozę dodaj nowy na te 1100px jak pisał szymon i git bedzie

2024-01-18 18:43 UTC, kamil-ciesla approved these changes, later dismissed

2024-01-20 19:33 UTC, kamil-ciesla approved these changes

2024-01-21 00:24 UTC, merged