feature: add desktop item tile
UEK-i-team/team-homepage pull request #22
Opened 2024-01-15 10:35 UTC by SylwiaHaracz

2024-01-15 14:32 UTC, szymonqqaz reviewed
Jeśli są większe zdjęcia, to bardzo rozciągają element, trzeba ograniczyć wysokość 
<img width="1496" alt="image" src="https://github.com/UEK-i-team/team-homepage/assets/42467247/e44962e4-a5da-45b9-a002-57e3673395e2">

2024-01-15 14:32 UTC, szymonqqaz commented on src/components/ItemTile/ItemTile.module.scss
> +@media (max-width: 768px){
Aby nie powtarzać tak dużo kodu css, to proponuję usunąć to media query, a w tym drugim media query dla desktopu poniżej tylko poustawiać wartości, które się zmieniają względem pierwszego. Bo takie wartości jak `display flex` czy `align-items` pozostają takie same więc nie ma co się powtarzać.

2024-01-15 14:32 UTC, szymonqqaz commented on src/components/ItemTile/ItemTile.module.scss
> +  .container:nth-child(odd) {
Super pomysł z takim rozwiązaniem

2024-01-15 21:20 UTC, kamil-ciesla commented
Tekst powinien zawsze zaczynać się od lewej strony, tak jak na figmie

twoja wersja:
<img width="1488" alt="image" src="https://github.com/UEK-i-team/team-homepage/assets/67390569/56a3676f-461f-4661-8e42-eb946e853969">

figma:
<img width="719" alt="image" src="https://github.com/UEK-i-team/team-homepage/assets/67390569/a6ef97c4-6319-43ae-92f8-ff9fb745223c">

2024-01-15 21:23 UTC, kamil-ciesla commented
u mnie proporcje są inne niż na figmie, obraz zajmuje za dużo miejsca. Może to kwestia użytego przeze mnie obrazu, anyway, skalowanie obrazów to nie jest prosta kwestia. Może narazie spróbuj wymusić stałe proporcje (obraz może ulec zniekształceniu), może to będzie okej, jeśli nie to może będziemy musieli wstawiać odpowiednio spreparowane obrazy
 
 ref
 
<img width="1507" alt="image" src="https://github.com/UEK-i-team/team-homepage/assets/67390569/06965231-88de-4686-912c-e68d97b4da89">

2024-01-17 18:46 UTC, kamil-ciesla commented
Almost perfect :)

Popraw jeszcze border radiusy dla obrazów, tak żeby zaokrąglone byly na kątach, a nie po srodku. (weź pod uwagę że strony się zamieniaja, wiec przetestuj dla 3 ItemTile) powinno być tak samo jak w figmie (jak co to dolne rogi przy kątach kafelka też są zaokraglone, tylko na obrazie na figmie nie jest to zbytnio widoczne

![image](https://github.com/UEK-i-team/team-homepage/assets/67390569/d584b49e-ebf4-4b9e-b702-de2b2781d3c0)

2024-01-21 13:54 UTC, kamil-ciesla commented
Usuń jeszcze padding między obrazem a kafelkiem, tak aby obraz przylegał bezpośrednio do krawędzi.
<img width="576" alt="image" src="https://github.com/UEK-i-team/team-homepage/assets/67390569/4935dc15-2515-49d5-afe1-39fc43d81900">

2024-01-21 13:56 UTC, kamil-ciesla commented
Brakuje jeszcze dark theme, ale to nie jest część twojego taska, jak zaciągniesz najnowsze zmiany z developa to powinien zadziałać dark theme, dlatego polecam zrobić rebase troche wcześniej i przetestować

2024-01-21 14:00 UTC, kamil-ciesla requested changes
apply suggested change

2024-01-27 17:15 UTC, kamil-ciesla approved these changes
LGTM :)

2024-01-27 17:16 UTC, merged