feature: carousel
UEK-i-team/team-homepage pull request #30
Opened 2024-01-25 18:00 UTC by JakubOtto

2024-02-14 15:14 UTC, szymonqqaz requested changes
@JakubOtto Fajnie działa ta karuzela! Dodałem parę komentarzy

@JakubOtto @kamil-ciesla @TheFenix2000 
Po co robimy tę blokadę przed spamem? Mnie to np. frustruje, że nie mogę szybko przeskoczyć po zdjęciach

2024-02-14 15:14 UTC, szymonbrud commented on src/components/Carousel/Carousel.js
> +              {i === index ? (
Można uprościć ten poniższy fragment w taki sposób:
```
<div className={indicator}>
    {i === index && <div className={indicatorFill} />}
</div>
```

2024-02-14 15:14 UTC, szymonbrud commented on src/components/Carousel/Carousel.js
> +  const handlePrevious = () => {
Każdą funkcję trzeba opakować w hooka `useCallback`, ten hook pomaga w optymalizacji, ponieważ przy każdej zmianie stanu, która jest wywołana poprzez przewinięcie zdjęcia, wszystkie funkcje na nowo są interpretowane. Chcemy, aby te funkcje były interpretowane na nowo tylko wtedy kiedy jest to konieczne, czyli kiedy w funkcji wykorzystujemy np. stan, który został zmieniony. 
Daje linka do dokumentacji reacta: https://react.dev/reference/react/useCallback
jeśli byś miał z tym problemy to dawaj znać

2024-02-14 15:14 UTC, szymonqqaz commented on src/components/Carousel/Carousel.js
> +      setIndex(newIndex >= length ? 0 : newIndex);
Gdy zmieniamy stan na bazie stanu poprzedniego dobrym podejściem jest użycie notacji
 `setIndex(prev => prev + 1)` 
 1. Niweluje to ryzyko błędów i niepoprawnie zmienianych wartości
 2. Zwiększa wydajność aplikacji
 
 Więc w tym przykładzie użycie tego mogłoby wyglądać tak:
 ```
 setIndex(prev => prev + 1 >= length ? 0 : prev + 1);
 ```
 
 Zmień proszę resztę podobnych zmian stanów w kodzie na taką notację

2024-02-14 18:29 UTC, TheFenix2000 commented
> @JakubOtto Fajnie działa ta karuzela! Dodałem parę komentarzy
> 
> @JakubOtto @kamil-ciesla @TheFenix2000 Po co robimy tę blokadę przed spamem? Mnie to np. frustruje, że nie mogę szybko przeskoczyć po zdjęciach

jest dostatecznie szybko, wszystko jest tak jak powinno
bo co mają użytkownicy spamować zdjeciami i obciążać przeglądarkę, która je bedzie tam wrzucać kilka razy an sekundę?

2024-02-14 19:49 UTC, TheFenix2000 requested changes
Proszę też rozwiąż konflikty przy okazji **rebese'a** do developa

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.js
> +import './Carousel.module.scss';
niepoprawne użycie styl

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.js
> +import ph from './imgs/ph.jpg';
images powinny być przekazywane w propsie jako arr obrazków

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.js
> +            <img
używamy komponentu GatsbyImage -> patrz na itemTile

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.js
> +              onClick={() => setIndex(i)}
po co to tutaj, nic nie robi?

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.module.scss
> +  background-color: black;
używamy $vars z theme.scss pliku, proszę zmień na odpowiedni/dodaj kolor

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.module.scss
> +  background-color: white;
analogicznie jak wyżej

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/Carousel.module.scss
> +  background-color: rgb(63, 66, 66);
analogicznie jak wyżej

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Carousel/imgs/ph.jpg
oczywiscie w ostatecznej wersji pliki do usuniecia

2024-02-14 19:49 UTC, TheFenix2000 commented on src/components/Project/Project.js
dodaj proszę tutaj obsługę - przekazanie - obrazków z propsa do karuzeli, bo wiele projektów może używać tego komponentu i każdy może chcieć podać inne obrazki, nie będę po to robić taska specjalnie na jednego propsa

2024-02-14 19:49 UTC, TheFenix2000 commented on src/pages/index.js
oczywiscie w finalnej wersji do usuniecia ze strony głównej

2024-02-15 16:49 UTC, kamil-ciesla approved these changes, later dismissed

2024-02-15 16:49 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +      }, 500);
jako, że obrazki ju będą zapisane w przeglądarce, szybkie przeskakiwanie nie będzie obciążać serwera, mysle ze 100 milisekund poprawi troche feeling klikania

2024-02-15 16:49 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +      <div className={`${inner}`}>
popraw proszę nazwę na bardziej deskryptywną

2024-02-15 16:49 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +        </div>
myśle ze te klasy css powinny byc inaczej podzielone poniewaz parent div posiada zarówno klase leftArrow jak i arrowContainer, leftArrow powinno być klasą opisujacą LeftArrMobile. Chyba, że ta klasa ma opisywac container, wtedy leftArrowContainer byloby dobra nazwa

2024-02-16 17:28 UTC, TheFenix2000 requested changes
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/056f8909-a6ef-4a3d-8d72-5e4a0bd52052)
error w konsoli przy przeskakujących zdjęciach

EDIT
Not related

2024-02-16 17:48 UTC, TheFenix2000 approved these changes, later dismissed

2024-02-16 20:13 UTC, kamil-ciesla requested changes
also remove changes from index.js

2024-02-16 20:13 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +export const Carousel = ({ images }) => {
dodaj komentarz czym są images, czy to obiekty, ścieżki czy coś innego.
chodzi o to żeby osoba uzywajaca komponentu wiedziala jak przekazać obrazy

2024-02-16 20:13 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +  const handleNext = useCallback(() => {
change to handleNextImage

2024-02-16 20:13 UTC, kamil-ciesla commented on src/components/Carousel/Carousel.js
> +  const length = images.length;
change to imagesLength

2024-02-16 20:27 UTC, szymonqqaz commented
> > @JakubOtto @kamil-ciesla @TheFenix2000 Po co robimy tę blokadę przed spamem? Mnie to np. frustruje, że nie mogę szybko przeskoczyć po zdjęciach
> 
> jest dostatecznie szybko, wszystko jest tak jak powinno bo co mają użytkownicy spamować zdjeciami i obciążać przeglądarkę, która je bedzie tam wrzucać kilka razy an sekundę?

@TheFenix2000 No to imo nie nasz interes co kto robi ze swoją przelądarką, dla jednych to może być dobra prędkość, a drudzy będą chcieli przelecieć na szybko te zdjęcia, ja się złapałem parę razy na tym że klikałem w następne zdjęcie a animacja poprzedniego się jeszcze nie skończyła i musiałem czekać oraz klikać jeszcze raz

2024-02-18 10:37 UTC, szymonqqaz approved these changes, later dismissed

2024-02-19 10:09 UTC, TheFenix2000 commented
> > > @JakubOtto @kamil-ciesla @TheFenix2000 Po co robimy tę blokadę przed spamem? Mnie to np. frustruje, że nie mogę szybko przeskoczyć po zdjęciach
> > 
> > 
> > jest dostatecznie szybko, wszystko jest tak jak powinno bo co mają użytkownicy spamować zdjeciami i obciążać przeglądarkę, która je bedzie tam wrzucać kilka razy an sekundę?
> 
> @TheFenix2000 No to imo nie nasz interes co kto robi ze swoją przelądarką, dla jednych to może być dobra prędkość, a drudzy będą chcieli przelecieć na szybko te zdjęcia, ja się złapałem parę razy na tym że klikałem w następne zdjęcie a animacja poprzedniego się jeszcze nie skończyła i musiałem czekać oraz klikać jeszcze raz

teraz jest 200 milisec co jest wystarczająco szybko by juz działy się dziwne przeskoki, szybciej nei ma sensu

2024-02-19 10:29 UTC, TheFenix2000 approved these changes, later dismissed

2024-02-26 11:13 UTC, kamil-ciesla requested changes

2024-02-26 11:13 UTC, kamil-ciesla commented on src/pages/index.js
> -      <OurProjects />
te komponenty pochodzą z najnowszego developa, przywróć je proszę (linie 7,8,14,15)

2024-02-26 17:32 UTC, kamil-ciesla approved these changes

2024-02-26 18:05 UTC, merged