feature: add light and dark mobile background
UEK-i-team/team-homepage pull request #34
Opened 2024-01-29 16:00 UTC by grochalapiotr

Added light and dark variant of background for mobile view

2024-01-31 20:54 UTC, TheFenix2000 requested changes, later dismissed

2024-01-31 20:54 UTC, TheFenix2000 commented on src/assets/images/background-dark-mobile.png
są białe paski na mobilce po bokach
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/3a560299-a0cd-4d41-8386-fb5752ed6640)

2024-01-31 20:54 UTC, TheFenix2000 commented on src/assets/images/background-dark-mobile.png
nei jest to podobne do tego na desktopie, nie wiem, dla mnei nie wygląda za dobrze, czemu nie dać po prostu tego co jest na desktopie? @szymonqqaz

2024-01-31 20:54 UTC, TheFenix2000 commented on src/assets/styles/baseStyles.scss
> +@media (max-width: 768px) {
po co dodawać to samo, wystarczy jak juz to zmienić obrazek

2024-01-31 22:14 UTC, szymonqqaz requested changes, later dismissed

2024-01-31 22:14 UTC, szymonqqaz commented on src/assets/images/background-dark-mobile.png
@grochalapiotr ustaliliśmy z Michałem, żeby ten background został. Tylko proponuję zmienić wszystkie te backgroundy na SVG. Powinny się szybciej ładować niż grafika PNG. Tak mi się wydaje przynajmniej. 😅

2024-01-31 22:14 UTC, szymonqqaz commented on src/assets/images/background-dark-mobile.png
@grochalapiotr Z ciekawości powalczyłem z tym problemem, udało mi się zwalczyć białe paski przy exporcie z Figmy. Stworzyłem tam specjalny element, który już exportuje się poprawnie. Link do niego: https://www.figma.com/file/JdRVBMTcW39D01KrtAPJTb/webpage---i%3A%3Ateam?type=design&node-id=1590-860&mode=design&t=CJAfEZstfKnWEE9u-4

2024-01-31 22:19 UTC, szymonqqaz commented on src/assets/styles/baseStyles.scss
> +    background-position: center;
Czy to `background-position: center` jest potrzebne? Jeśli nie to proponuję nie wyrzucić z uwagi na to że, jeśli jest ten styl ustawiony to, wtedy tło nie zaczyna się od początku tak jak powinno, tylko od środka.

2024-02-12 22:41 UTC, kamil-ciesla approved these changes

2024-02-12 22:41 UTC, merged