feature: change language button
UEK-i-team/team-homepage pull request #36
Opened 2024-02-02 12:53 UTC by TheWoxPL

- removed old button and unnecessary code in css and js.
- added new button to website
- added globe.svg

2024-02-02 15:51 UTC, szymonqqaz requested changes

2024-02-02 15:51 UTC, szymonqqaz commented on src/components/Navbar/Navbar.js
> +          <button onClick={() => toggleTheme()} className={themeButton}>
`onClick={() => toggleTheme()}` można zmienić na `onClick={toggleTheme}` będzie prościej zapisane

2024-02-02 15:51 UTC, szymonqqaz commented on src/components/Navbar/Navbar.js
> +  const handleButtonChange = () => {
Tę funkcję można wziąć z hook `useCallback`. I jako wyzwalacze dodać `switchLanguage` oraz `currentLanguage` aby funkcja poprawnie działała. 
Przykład: 
```
const handleButtonChange = useCallback(() => {
    if (currentLanguage === 'pl') {
      switchLanguage('en');
      setCurrentLanguage('en');
    } else {
      switchLanguage('pl');
      setCurrentLanguage('pl');
    }
}, [switchLanguage, currentLanguage])
```
Poprawi to wydajność

2024-02-12 10:18 UTC, TheFenix2000 requested changes
Popraw te 3 i można mergować imo

2024-02-12 10:18 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.js
> +            <span>{currentLanguage === 'pl' ? 'Polski' : 'English'}</span>
tutaj dałbym to w translate to i18 np `lang` czy coś, kiedy mamy translację, to unikamy wstawianie tekstu z palca

2024-02-12 10:18 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.module.scss
Nie ma wersji na mobilkę? Bo to jest za duże na taką wersję imo 
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/4328a21b-14e2-4d03-ba35-bfbac7970407)

2024-02-12 10:20 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.js
zrebesuj na najnowszego developa

2024-03-03 13:20 UTC, TheFenix2000 approved these changes
lgtm

2024-03-03 16:09 UTC, szymonqqaz approved these changes

2024-03-03 23:15 UTC, merged