Feature/create mobile main page view
UEK-i-team/team-homepage pull request #39
Opened 2024-02-04 19:39 UTC by dontmentio

Add main page view using WhoWeAre and new OurProjects components

2024-02-04 20:05 UTC, kamil-ciesla commented
na desktop view przy zmianie theme jest przesunięcie WhoWeAre component.
można to odrazu zrobić w tym PRze i będziemy mieli widok mobile i desktop za jednym zamachem, ewentualnie zrobić oddzielnego taska na fixa

2024-02-04 20:14 UTC, kamil-ciesla approved these changes, later dismissed

2024-02-04 21:05 UTC, szymonqqaz requested changes
Wrzucam screeny, gdzie trzeba poprawić wymiary względem figmy.
![change](https://github.com/UEK-i-team/team-homepage/assets/42467247/baeec413-1e41-4ba8-844c-0c5a00798eed)
![change2](https://github.com/UEK-i-team/team-homepage/assets/42467247/c3a95e94-d28e-4129-89a2-56ff1eee39e8)

2024-02-04 23:52 UTC, szymonqqaz approved these changes
Po zmianach wygląda sztosik

2024-02-05 18:23 UTC, kamil-ciesla approved these changes

2024-02-05 22:59 UTC, merged