fix: repair tabbing and outline highlight
UEK-i-team/team-homepage pull request #45
Opened 2024-03-04 00:12 UTC by TheWoxPL

- remove sidebar from tabbing when desktop view
- repair bad looking outlines of few elements
- make a new style of outline highlight

2024-03-04 19:13 UTC, TheWoxPL commented
W karuzeli nie ma obsługi przycisków tabem. Poprawić to czy bedzie to osobny fix?
![image](https://github.com/UEK-i-team/team-homepage/assets/92746206/43fbc702-1ac9-4889-b430-9739fa7cf9a8)

2024-03-11 17:11 UTC, TheFenix2000 requested changes
zrebesuj i mozna mergować

2024-03-11 17:11 UTC, TheFenix2000 commented on src/assets/styles/baseStyles.scss
> +@use 'theme';
daj importa na theme i relatywna ścieżkę jak w innych komponentach

2024-03-11 17:11 UTC, TheFenix2000 commented on src/assets/styles/baseStyles.scss
> +  outline-color: theme.$pink_100;
jak zmienisz theme to wtedy bez `theme.` tylko sama zmienna

2024-03-11 17:12 UTC, TheFenix2000 commented
> W karuzeli nie ma obsługi przycisków tabem. Poprawić to czy bedzie to osobny fix? ![image](https://private-user-images.githubusercontent.com/92746206/309873532-43fbc702-1ac9-4889-b430-9739fa7cf9a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzc0MDUsIm5iZiI6MTcxMDE3NzEwNSwicGF0aCI6Ii85Mjc0NjIwNi8zMDk4NzM1MzItNDNmYmM3MDItMWFjOS00ODg5LWI0MzAtOTczOWZhN2NmOWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE3MTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Yjc1MTY0YTA2ZmU1ZjQxMjY0MTIyN2U5OGViNmVkNWFhNDRhNTc1YzNhM2EwOTlhNjExOTFjMzY4NDIyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OvgwLiMcKYNh5CkT5qY2d-nGQHxTT6wA9AnyHJ0ApVM)

to trzeba dodać, ale to w osobnym tasku komuś bo to malo roboty

2024-03-11 17:22 UTC, TheFenix2000 approved these changes
lgtm

2024-03-11 17:25 UTC, merged