Fix/resize clickable elements
UEK-i-team/team-homepage pull request #50
Opened 2024-03-14 15:51 UTC by h3770k1k1

zmieniłam ikonki githuba i facebooka w footerze na te co są na figmie (30 x 30 ), hamburgermenu żeby miał 25 x 25, close buttona, themeicon i zmieniłam languageButton - teraz na wersji mobilnej jest taki sam jak na desktopie, żeby był odpowiedniej wielkości ale to niewiem czy jest ok, chyba niewygląda źle

2024-03-25 11:35 UTC, TheFenix2000 commented
Teraz:
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/3fea2130-24d7-44b8-a8b4-f3606d864978)

Wcześniej:
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/1c820734-8966-4034-81c4-cc351be77843)
@h3770k1k1

2024-03-25 11:41 UTC, TheFenix2000 requested changes
rebase pewnei na koniec, oprócz fixów na te style, to od strony kodowej lgtm

2024-03-25 11:41 UTC, TheFenix2000 commented on src/components/Footer/Footer.module.scss
> +    color: rgb(0, 0, 0);
czemu tak a nie z vara z `theme` pliku?

2024-03-25 11:41 UTC, TheFenix2000 commented on src/components/SidebarMenu/SidebarMenu.module.scss
coś tu ewidentnie się zwaliło bo jest tak, jak w komentarzu wysłałem

2024-03-25 11:41 UTC, TheFenix2000 commented on src/components/SidebarMenu/SidebarMenu.module.scss
znalazłem go, uciekł do boku, poza tym header jest zepsuty, ikonki jakieś małe się wydają i z abardzo na dole, ale lepiej wyglądają okrągłe fakt.
![image](https://github.com/UEK-i-team/team-homepage/assets/49104061/f342e1d0-32d0-4b94-a394-aa5ae19b606f)

2024-04-07 15:50 UTC, h3770k1k1 commented on src/components/SidebarMenu/SidebarMenu.module.scss
na developie teraz jest tak
![erf4g](https://github.com/UEK-i-team/team-homepage/assets/87210052/903e333d-8dd2-457f-9294-187b5f474c69)
a na figmie: 
![image](https://github.com/UEK-i-team/team-homepage/assets/87210052/0a4d2876-ca51-4e77-ad71-b5f0aa0ca9ed)

2024-04-07 15:55 UTC, h3770k1k1 commented on src/components/SidebarMenu/SidebarMenu.module.scss
względem figmy nie są jakoś na dole i są 30 x 30 czyli i tak większe niż na figmie i większe niż minimum tego co powinno być według tej dostępności
ale jak powiesz jak powiększyć to powiększę .^.

2024-04-07 19:57 UTC, TheFenix2000 requested changes
jeszcze kilka rzeczy zauważylem

2024-04-07 19:57 UTC, TheFenix2000 commented on src/components/Footer/Footer.module.scss
> +    a * {}
do usuniecia skoro puste

2024-04-07 19:57 UTC, TheFenix2000 commented on src/components/Navbar/Navbar.module.scss
> +    width: 20px;
po co 2 width, jeden juz jest wyżej

2024-04-07 19:57 UTC, TheFenix2000 commented on src/components/SidebarMenu/SidebarMenu.module.scss
to zostawmy tak jak na figmie, nei powiekszaj

2024-04-09 13:15 UTC, TheFenix2000 commented
zamykam z uwagi na problemy techniczne, nowy pr -> pull #62

2024-04-09 13:15 UTC, closed without merging