blending text
UEK-i-team/team-homepage pull request #53
Opened 2024-03-17 22:42 UTC by TheWoxPL

- changed line height of text

2024-03-17 22:47 UTC, TheWoxPL commented
Dodałem tekst lorem ipsum do sprawdzania tekstu i usunę ten commit jak bedzie ostatecznie wszystko dobrze. Zmieniłem wysokość lini tylko w itemtile na desktop, reszta wg mnie wygląda dobrze.

2024-03-25 11:17 UTC, TheFenix2000 requested changes
popraw i git

2024-03-25 11:17 UTC, TheFenix2000 commented on src/components/ItemTile/ItemTile.module.scss
> +@media (max-width: 768px) {
zmień na breakpointa z pliku `theme`

2024-03-25 11:17 UTC, TheFenix2000 commented on src/components/ItemTile/ItemTile.module.scss
> +@media (min-width: 769px) {
analogicznie

2024-03-25 11:17 UTC, TheFenix2000 commented on src/components/ItemTile/ItemTile.module.scss
> +@media (max-width: 768px) {
w sumie nie twój komponent ale to szybko wstawić

2024-03-25 13:19 UTC, TheWoxPL commented on src/components/ItemTile/ItemTile.module.scss
> +@media (max-width: 768px) {
> zmień na breakpointa z pliku `theme`

Zmieniłem na breakpoint tabletu (700px) i działa, tylko w css jest pomieszane min-width z max-width i dla pewnego rozmiaru okna itemtile sie rozjeżdza. 
![image](https://github.com/UEK-i-team/team-homepage/assets/92746206/ea01830f-a19b-4446-92bb-94f37aa41191)
Zauważyłem że css bez breakpointa jest dla tabletu/desktop a nie dla mobile tak jak w pozostałych komponentach. 
@TheFenix2000 
Te zmiany mam u siebie, nie pushowalem ich na githuba.

2024-04-03 13:18 UTC, TheWoxPL commented
Usunąłem ostatniego commit'a z lorem ipsum oraz dokonałem rebase.

2024-04-15 15:04 UTC, TheFenix2000 approved these changes
lgtm

2024-04-15 16:21 UTC, merged