feature: design borders on item tile
UEK-i-team/team-homepage pull request #54
Opened 2024-03-23 14:38 UTC by h3770k1k1

2024-03-24 23:50 UTC, TheWoxPL commented
Przeglądałem jak wyglada obramowanie na telefonie i zauważyłem, że itemtile sie rozjeżdza oraz dochodzi dodatkowy odstęp w środku komponentu.
![image](https://github.com/UEK-i-team/team-homepage/assets/92746206/09c70906-3910-455a-b65c-4a6daa5fb823)
![image](https://github.com/UEK-i-team/team-homepage/assets/92746206/e1dae1a9-3ba9-45bb-b54b-3a72f8719102)

2024-03-25 11:19 UTC, TheFenix2000 commented
> Przeglądałem jak wyglada obramowanie na telefonie i zauważyłem, że itemtile sie rozjeżdza oraz dochodzi dodatkowy odstęp w środku komponentu. ![image](https://private-user-images.githubusercontent.com/92746206/316352079-09c70906-3910-455a-b65c-4a6daa5fb823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjU4MTAsIm5iZiI6MTcxMTM2NTUxMCwicGF0aCI6Ii85Mjc0NjIwNi8zMTYzNTIwNzktMDljNzA5MDYtMzkxMC00NTVhLWI2NWMtNGE2ZGFhNWZiODIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwODE1MjZmMjY5OGVhNzEzYzY1YmM2ODlhNWY0MTk2ZTE2ZjI4MTQ2ODBkOTljZWFhNzkyZmRkMmQyMDIyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.noN-ZdqM_iZF1I7ZE_C5lAnTOT326TbyTmeyPJVBkgc) ![image](https://private-user-images.githubusercontent.com/92746206/316352153-e1dae1a9-3ba9-45bb-b54b-3a72f8719102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjU4MTAsIm5iZiI6MTcxMTM2NTUxMCwicGF0aCI6Ii85Mjc0NjIwNi8zMTYzNTIxNTMtZTFkYWUxYTktM2JhOS00NWJiLWI1NGItM2E3MmY4NzE5MTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3N2NiZjA0ZjliZTIzMTkzMTU3YTFjODdiYTM0ZDJlYTBjOTI5NzNmOTIwMzNhZTM5ZDBmNTU5NTU3NGIzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMnLzfAlta52w0blGJfVkAWqQkhvNAdpWGi7fMI6h10)

zrobi się z tego dziś taska, dobrze że zauważyłeś

2024-03-25 11:23 UTC, TheFenix2000 commented
@h3770k1k1 w newsach teraz item tile nie jest na środku, trzeba by to fixnąć

2024-03-25 11:23 UTC, TheFenix2000 commented
@szymonqqaz zerkniesz tutaj, bo nie jestem pewien co do tej kolorystyki, a wolę bez twojego wprawnego oka nie mergować

2024-04-07 18:28 UTC, TheFenix2000 requested changes
tylko wyśrodkować itemTile i zrobić rebase

2024-04-24 20:04 UTC, TheFenix2000 approved these changes
lgtm ^^

2024-04-24 20:04 UTC, merged